name: "fastfetch"
version: "2.53.0"
description: "A fast and customizable fetch tool."

source:
  url: "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.53.0.tar.gz"

dependencies:
  build:
    - cmake
    - make
    - gcc
  runtime: []

build:
  out_of_source: true
  steps:
    - "cmake .."
    - "make"

install:
  steps:
    - "make install"
