name: fastfetch
version: 2.53.0
description: a tool for stupid nerds and arch + hyprland users

source:
  url: https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.53.0.tar.gz

dependencies:
  build: []
  runtime: []

build: |
  cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  make -j$(nproc)
  make install
