name: fastfetch
version: 2.53.0
description: a tool for stupid nerds and arch + hyprland users

source:
  url: https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.53.0.tar.gz
  sha256: "5d2c7915afa3565542420957d0c1624aaae2e65dfa938910abf84a8e30ea1b18"

dependencies:
  build: []
  runtime: []

build: |
  cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  make -j$(nproc)
  make install
