name: json-c
version: 0.18
description: The JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects. 

source:
  url: https://s3.amazonaws.com/json-c_releases/releases/json-c-0.18.tar.gz

dependencies:
  out_of_source: true
  build: [cmake]
  runtime: []

build: |
  cmake -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_BUILD_TYPE=Release -D BUILD_STATIC_LIBS=OFF
  make -j4
  make install

