name: libptytty
version: 2.0
description: The libptytty package provides a library that allows for OS independent and secure pty/tty and utmp/wtmp/lastlog handling. 

source:
  url: http://dist.schmorp.de/libptytty/libptytty-2.0.tar.gz

dependencies:
  build:
  - cmake
  runtime: []

build: |
  cmake -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_BUILD_TYPE=Release -D PT_UTMP_FILE:STRING=/run/utmp ..
  make -j4

install: |
  make install
