name: libptytty
version: 2.0
description: The libptytty package provides a library that allows for OS independent and secure pty/tty and utmp/wtmp/lastlog handling.

source:
  type: url
  location: http://dist.schmorp.de/libptytty/libptytty-2.0.tar.gz
  hash_type: md5
  verification: 2a7f3f3c0d3ef71902da745dc7959529

dependencies:
  build:
    - cmake
  runtime: []

build:
  out_of_source: true
  steps:
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DPT_UTMP_FILE:STRING=/run/utmp ..
    - make

install:
  steps:
    - make install
