name: make-ca
version: 1.16.1
description: Public Key Infrastructure (PKI) is a method to validate the authenticity of an otherwise unknown entity across untrusted networks. PKI works by establishing a chain of trust, rather than trusting each individual host or entity explicitly. In order for a certificate presented by a remote entity to be trusted, that certificate must present a complete chain of certificates that can be validated using the root certificate of a Certificate Authority (CA) that is trusted by the local machine. 

source:
  url: https://github.com/lfs-book/make-ca/archive/v1.16.1/make-ca-1.16.1.tar.gz
  format: tar.gz

dependencies:
  build: [libtasn, p11-kit]
  runtime: []

build: |
  make install
  install -vdm755 /etc/ssl/local
  /usr/sbin/make-ca -g
  systemctl enable update-pki.timer
  
