name: gcc
version: 15.2.0
description:  The GCC package contains the GNU Compiler Collection.

source:
  url: https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.xz
  format: tar.xz

dependencies:
  build: []
  runtime []

build: |
  case $(uname -m) in
    x86_64)
      sed -i.orig '/m64=/s/lib64/lib/' gcc/config/i386/t-linux64
    ;;
  esac
  mkdir build
  cd build
  ../configure --prefix=/usr --disable-multilib --with-system-zlib --enable-default-pie  --enable-default-ssp --enable-host-pie --disable-fixincludes --enable-languages=c,c++,fortran,go,objc,obj-c++,m2
    make -j$(nproc)
    make install
    mkdir -pv /usr/share/gdb/auto-load/usr/lib
    mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
    chown -v -R root:root /usr/lib/gcc/*linux-gnu/15.2.0/include{,-fixed}
    ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/15.2.0/liblto_plugin.so /usr/lib/bfd-plugins/
    

