name: libevent
version: 2.1.12
description: libevent is an asynchronous event notification software library. The libevent API provides a mechanism to execute a callback function when a specific event occurs on a file descriptor or after a timeout has been reached. Furthermore, libevent also supports callbacks due to signals or regular timeouts. 

source:
  url: https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
  format: tar.gz

dependencies:
  build: []
  runtime []

build: | 
  sed -i 's/python/&3/' event_rpcgen.py
  ./configure --prefix=/usr --disable-static &&
make

