name: cracklib
version: 2.10.3
description:  The CrackLib package contains a library used to enforce strong passwords by comparing user selected passwords to words in chosen word lists. 

source:
  url: https://github.com/cracklib/cracklib/releases/download/v2.10.3/cracklib-2.10.3.tar.xz

dependencies:
  build: []
  runtime: []

build: |
  CPPFLAGS+=' -I /usr/include/python3.13'
  ./configure --prefix=/usr --disable-static
  make -j4
  make install

