name: cryptsetup
version: 2.8.1
description: cryptsetup is used to set up transparent encryption of block devices using the kernel crypto API. 

source:
  url: https://www.kernel.org/pub/linux/utils/cryptsetup/v2.8/cryptsetup-2.8.1.tar.xz

dependencies:
  build: [json-c, lvm2, popt]
  runtime: []

build: |
  ./configure --prefix=/usr --disable-ssh-token --disable-asciidoc
  make -j4
  make install
